name: FastF1 Cache Cleanup

on:
  schedule:
    # Clean cache weekly on Sundays at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    name: Clear FastF1 Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check cache size
        run: |
          if [ -d "cache" ]; then
            SIZE=$(du -sh cache | cut -f1)
            echo "Current cache size: $SIZE"
          else
            echo "No cache directory found"
          fi

      - name: Clean old cache files
        run: |
          # Remove cache files older than 30 days
          if [ -d "cache" ]; then
            find cache -type f -mtime +30 -delete
            echo "Cleaned cache files older than 30 days"

            # Show new size
            if [ -d "cache" ]; then
              SIZE=$(du -sh cache | cut -f1)
              echo "New cache size: $SIZE"
            fi
          fi

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cache/ || true
          git commit -m "chore: clean old FastF1 cache files" || echo "No changes to commit"
          git push || echo "No changes to push"
